name: Build (PR)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
